### ISSUE TITLE
Consider alternative transports/formats/markup for TAP

### ISSUE THREAD

**Issue by jonathanKingston** [TestAnything/Specification#1]
Many discussions have been raised around this time and time again however I would finally like to settle this.

Currently YAML is mentioned in the TAP 13 specification on the site: http://testanything.org/tap-version-13-specification.html

However this format for debug is unspecified, which raises a few questions:
- Should this format be specified at all or should it just be debug?
  - or widened to support whatever the application decides to throw out?
- Should other formats be considered for the YAML block?
- Should the whole TAP output be standardised across multiple transports much like schema.org has done for its data specifications.

Relevant issues:
- https://github.com/TestAnything/testanything.github.io/pull/6
- https://github.com/substack/tape/issues/91

Other transports worth mentioning:
- https://thrift.apache.org/
- https://developers.google.com/protocol-buffers/docs/techniques#streaming

YAML format:
What I wrote for ESLint as a debug is probably a good starting place for a discussion:
`https://github.com/eslint/eslint/blob/master/lib/formatters/tap.js`
```
                    message: <<message name>>
                    severity: <<severity name>>
                    data:
                        line: <<line number>>
                        column: <<column number>>
                        ruleId: <<rule number>>
```

Thanks for all the input so far: @jcelliott and @TestAnything/owners
